version: "3"

services:
  database:
    container_name: app-database
    image: mongo:3
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: app-api
    image: node:18
    working_dir: /usr/src/app
    restart: always
    ports:
      - "3333:3333"
      - "9222:9222"
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://database:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    links:
      - database
    depends_on:
      - database
