version: "3"

services:
  database:
    container_name: app-database
    image: mongo:3
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: app-api
    build: .
    restart: always
    image: clean-node-api
    ports:
      - "3333:3333"
    command: npm start
    volumes:
      - ./dist:/usr/src/app/dist
    links:
      - database
    depends_on:
      - database
